spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://localhost:3306/user
    username:
      root
    password:
      20040217
sever:
  port: 8080
#  servlet:
#    context-path: